name: Backend Deploy (Spring Boot)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  EB_APP_NAME: todoapp-TodoApp
  EB_ENV_NAME: todoapp-TodoApp-Env
  AWS_REGION: eu-west-1
  RDS_DB_INSTANCE_IDENTIFIER: todo-team-db

jobs:
  deploy:
    name: "Build and Deploy Spring Boot App"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::263883060207:role/github-actions-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Get RDS DB Endpoint
        id: rds_endpoint_step
        run: |
          DB_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier ${{ env.RDS_DB_INSTANCE_IDENTIFIER }} \
            --query 'DBInstances[0].Endpoint.Address' \
            --output text)
          echo "DB_ENDPOINT=$DB_ENDPOINT" >> "$GITHUB_ENV"
          echo "Fetched RDS DB Endpoint: $DB_ENDPOINT"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Spring Boot Application
        run: |
          cd secure-team-3-todo-api/
          mvn clean install -DskipTests

      - name: Create EB Deployment Bundle
        run: |
          BUILD_BUNDLE_DIR="eb-bundle-staging"
          mkdir -p "$BUILD_BUNDLE_DIR"
          cd secure-team-3-todo-api/
          JAR_FILE=$(find target -name "*.jar" -type f -print -quit)
          if [ -z "$JAR_FILE" ]; then
            echo "Error: Spring Boot JAR file not found."
            exit 1
          fi
          cp "$JAR_FILE" "${GITHUB_WORKSPACE}/$BUILD_BUNDLE_DIR/application.jar"
          cd "$GITHUB_WORKSPACE"
          DOCKERRUN_REPO_PATH="terraform/app_source/Dockerrun.aws.json"
          if [ ! -f "$DOCKERRUN_REPO_PATH" ]; then
            echo "Error: Dockerrun.aws.json not found."
            exit 1
          fi
          cp "$DOCKERRUN_REPO_PATH" "$BUILD_BUNDLE_DIR/"
          zip -j application.zip "$BUILD_BUNDLE_DIR"/*
          echo "Created application.zip."

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: ${{ env.EB_APP_NAME }}
          environment_name: ${{ env.EB_ENV_NAME }}
          version_label: github-sha-${{ github.sha }}
          deployment_package: application.zip
          region: ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
